use std::{collections::HashSet, time::Duration};

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Position {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

impl Position {
    pub const ORIGIN: Self = Self {
        x: 0.0,
        y: 0.0,
        z: 0.0,
    };

    pub const fn new(x: f64, y: f64, z: f64) -> Self {
        Self { x, y, z }
    }

    pub fn distance_to(self, other: Self) -> f64 {
        let dx = self.x - other.x;
        let dy = self.y - other.y;
        let dz = self.z - other.z;

        (dx * dx + dy * dy + dz * dz).sqrt()
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct SimulationResult {
    pub branches: Vec<BranchRunResult>,
}

impl SimulationResult {
    pub fn probability_mass(&self) -> f64 {
        self.branches
            .iter()
            .map(|result| result.branch.probability)
            .sum()
    }

    pub fn completed_probability_mass(&self) -> f64 {
        self.branches
            .iter()
            .filter(|result| result.reason == BranchStopReason::Complete)
            .map(|result| result.branch.probability)
            .sum()
    }

    pub fn blocked_probability_mass(&self) -> f64 {
        self.branches
            .iter()
            .filter(|result| result.reason != BranchStopReason::Complete)
            .map(|result| result.branch.probability)
            .sum()
    }

    pub fn is_complete(&self) -> bool {
        self.branches
            .iter()
            .all(|result| result.reason == BranchStopReason::Complete)
    }

    /// Expected damage from everything the simulator
    /// successfully resolved.
    ///
    /// If the simulation is blocked, this is only partial.
    pub fn expected_resolved_damage(&self) -> f64 {
        self.branches
            .iter()
            .map(|result| result.branch.probability * result.branch.total_damage_dealt())
            .sum()
    }

    pub fn expected_complete_damage(&self) -> Option<f64> {
        self.is_complete().then(|| self.expected_resolved_damage())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ProcKind {
    Atg,
    Ukulele,
    StickyBomb,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventTiming {
    Immediate,

    FixedDelay(Duration),
}

impl EventTiming {
    pub const fn delay(self) -> Duration {
        match self {
            Self::Immediate => Duration::ZERO,
            Self::FixedDelay(delay) => delay,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BranchStopReason {
    Complete,

    SimultaneousEvents { count: usize },

    UnsupportedBleedEvent,
}

#[derive(Debug, Clone, PartialEq)]
pub struct BranchRunResult {
    pub branch: CombatBranch,
    pub reason: BranchStopReason,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CombatBranch {
    /// Probability of reaching this branch.
    pub probability: f64,

    /// Resolution of the hit that created this branch.
    pub root_resolution: HitResolution,
    pub resolved_hits: Vec<HitResolution>,

    /// This branch's independent copy of target state.
    pub targets: TargetContext,

    /// Effects generated by the root hit that have not
    /// been resolved yet.
    pub current_time: Duration,
    pub pending_events: EventQueue,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AdvanceError {
    NoPendingEvents,

    /// We deliberately don't invent an ordering between
    /// events that occur at the same instant.
    SimultaneousEvents {
        count: usize,
    },

    /// Bleed is not yet represented as individual timed ticks.
    UnsupportedBleedEvent,
}

impl CombatBranch {
    pub fn total_damage_dealt(&self) -> f64 {
        self.root_resolution.damage_dealt()
            + self
                .resolved_hits
                .iter()
                .map(HitResolution::damage_dealt)
                .sum::<f64>()
    }

    pub fn pending_hits(&self) -> impl Iterator<Item = &GeneratedHit> {
        self.pending_events
            .iter()
            .filter_map(|event| match &event.effect {
                GeneratedEffect::Hit(hit) => Some(hit),
                _ => None,
            })
    }

    pub fn pending_bleeds(&self) -> impl Iterator<Item = &Bleed> {
        self.pending_events
            .iter()
            .filter_map(|event| match &event.effect {
                GeneratedEffect::Bleed(bleed) => Some(bleed),
                _ => None,
            })
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProcMask {
    seen: HashSet<ProcKind>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HitResolution {
    pub hit: Hit,
    pub target_health_before: f64,
    pub target_health_after: f64,
}

impl HitResolution {
    pub fn killed_target(&self) -> bool {
        self.target_health_before > 0.0 && self.target_health_after <= 0.0
    }

    pub fn damage_dealt(&self) -> f64 {
        self.target_health_before - self.target_health_after
    }
}

impl ProcMask {
    pub fn contains(&self, proc_kind: ProcKind) -> bool {
        self.seen.contains(&proc_kind)
    }

    pub fn insert(&mut self, proc_kind: ProcKind) {
        self.seen.insert(proc_kind);
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Hit {
    pub target: TargetId,
    pub attacker_base_damage: f64,
    pub proc_damage: f64,
    pub final_damage: f64,
    pub proc_coefficient: f64,
    pub proc_mask: ProcMask,
    pub crit: bool,
}

impl Hit {
    pub fn root(attacker_base_damage: f64, proc_damage: f64, proc_coefficient: f64) -> Self {
        Self::root_on_target(
            TargetId::PRIMARY,
            attacker_base_damage,
            proc_damage,
            proc_coefficient,
        )
    }

    pub fn root_on_target(
        target: TargetId,
        attacker_base_damage: f64,
        proc_damage: f64,
        proc_coefficient: f64,
    ) -> Self {
        assert!(attacker_base_damage >= 0.0);
        assert!(proc_damage >= 0.0);
        assert!(proc_coefficient >= 0.0);

        Self {
            target,
            attacker_base_damage,
            proc_damage,
            final_damage: proc_damage,
            proc_coefficient,
            proc_mask: ProcMask::default(),
            crit: false,
        }
    }

    pub fn apply_final_damage_multiplier(&mut self, multiplier: f64) {
        assert!(multiplier >= 0.0);

        self.final_damage *= multiplier;
    }

    pub fn spawn_total_damage_proc(
        &self,
        proc_kind: ProcKind,
        damage_multiplier: f64,
        proc_coefficient: f64,
    ) -> Option<Self> {
        self.spawn_total_damage_proc_on(proc_kind, self.target, damage_multiplier, proc_coefficient)
    }

    pub fn spawn_total_damage_proc_on(
        &self,
        proc_kind: ProcKind,
        target: TargetId,
        damage_multiplier: f64,
        proc_coefficient: f64,
    ) -> Option<Self> {
        assert!(damage_multiplier >= 0.0);
        assert!(proc_coefficient >= 0.0);

        if self.proc_mask.contains(proc_kind) {
            return None;
        }

        let mut proc_mask = self.proc_mask.clone();
        proc_mask.insert(proc_kind);

        let proc_damage = self.proc_damage * damage_multiplier;

        Some(Self {
            target,
            attacker_base_damage: self.attacker_base_damage,
            proc_damage,
            final_damage: proc_damage,
            proc_coefficient,
            proc_mask,
            crit: self.crit,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum AttackTargeting {
    SingleTarget,

    Chain { max_targets: u32, radius_m: f64 },

    Explosion { radius_m: f64, falloff: AreaFalloff },
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum AreaFalloff {
    None,
    SweetSpot,
}

impl AreaFalloff {
    pub fn multiplier(self, distance: f64, radius: f64) -> f64 {
        assert!(distance >= 0.0);
        assert!(radius > 0.0);

        match self {
            Self::None => 1.0,

            // RoR2 sweet-spot falloff:
            // inner 50% = 100%
            // outer 50% = 25%
            Self::SweetSpot => {
                if distance <= radius * 0.5 {
                    1.0
                } else {
                    0.25
                }
            }
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TargetId(u32);

impl TargetId {
    pub const PRIMARY: Self = Self(0);

    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    pub const fn value(self) -> u32 {
        self.0
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Target {
    id: TargetId,
    health: f64,
    max_health: f64,
    armor: f64,
    is_boss: bool,
    position: Position,
}

impl Target {
    pub fn new(id: TargetId, health: f64, max_health: f64, armor: f64, is_boss: bool) -> Self {
        assert!(max_health > 0.0);
        assert!(health >= 0.0);
        assert!(health <= max_health);

        Self {
            id,
            health,
            max_health,
            armor,
            is_boss,
            position: Position::ORIGIN,
        }
    }

    pub fn position(&self) -> Position {
        self.position
    }

    pub fn with_position(mut self, position: Position) -> Self {
        self.position = position;
        self
    }

    pub fn full_health(id: TargetId, max_health: f64) -> Self {
        Self::new(id, max_health, max_health, 0.0, false)
    }

    pub fn id(&self) -> TargetId {
        self.id
    }

    pub fn health(&self) -> f64 {
        self.health
    }

    pub fn max_health(&self) -> f64 {
        self.max_health
    }

    pub fn armor(&self) -> f64 {
        self.armor
    }

    pub fn is_boss(&self) -> bool {
        self.is_boss
    }

    pub fn health_fraction(&self) -> f64 {
        self.health / self.max_health
    }

    pub fn apply_damage(&mut self, damage: f64) {
        assert!(damage >= 0.0);

        self.health = (self.health - damage).max(0.0);
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct TargetContext {
    primary: TargetId,
    targets: Vec<Target>,
}

impl TargetContext {
    pub fn isolated() -> Self {
        Self::new(Target::full_health(TargetId::PRIMARY, 100.0), Vec::new())
    }

    pub fn with_secondary_targets(count: u32) -> Self {
        let primary = Target::full_health(TargetId::PRIMARY, 100.0);

        let secondary_targets = (1..=count)
            .map(|id| Target::full_health(TargetId::new(id), 100.0))
            .collect();

        Self::new(primary, secondary_targets)
    }

    pub fn new(primary: Target, secondary_targets: Vec<Target>) -> Self {
        let primary_id = primary.id();

        let mut targets = Vec::with_capacity(secondary_targets.len() + 1);

        targets.push(primary);
        targets.extend(secondary_targets);

        Self {
            primary: primary_id,
            targets,
        }
    }

    pub fn primary_target(&self) -> TargetId {
        self.primary
    }

    pub fn all_targets(&self) -> &[Target] {
        &self.targets
    }

    pub fn target(&self, id: TargetId) -> Option<&Target> {
        self.targets.iter().find(|target| target.id() == id)
    }

    pub fn target_mut(&mut self, id: TargetId) -> Option<&mut Target> {
        self.targets.iter_mut().find(|target| target.id() == id)
    }

    pub fn contact_targets(
        &self,
        source_target: TargetId,
        targeting: AttackTargeting,
    ) -> Vec<TargetId> {
        match targeting {
            AttackTargeting::SingleTarget => {
                vec![source_target]
            }

            AttackTargeting::Chain {
                max_targets,
                radius_m,
            } => {
                let source_position = self
                    .target(source_target)
                    .expect("source target must exist in target context")
                    .position();

                self.targets
                    .iter()
                    // Ukulele does not hit the target that triggered it.
                    .filter(|target| target.id() != source_target)
                    // Only targets inside the chain radius are eligible.
                    .filter(|target| source_position.distance_to(target.position()) <= radius_m)
                    .map(Target::id)
                    .take(max_targets as usize)
                    .collect()
            }

            AttackTargeting::Explosion { radius_m, .. } => {
                let center = self
                    .target(source_target)
                    .expect("explosion source target must exist")
                    .position();

                self.targets
                    .iter()
                    .filter(|target| center.distance_to(target.position()) <= radius_m)
                    .map(Target::id)
                    .collect()
            }
        }
    }
    pub fn targeting_damage_multiplier(
        &self,
        source_target: TargetId,
        target: TargetId,
        targeting: AttackTargeting,
    ) -> f64 {
        match targeting {
            AttackTargeting::SingleTarget | AttackTargeting::Chain { .. } => 1.0,

            AttackTargeting::Explosion { radius_m, falloff } => {
                let center = self
                    .target(source_target)
                    .expect("explosion source target must exist")
                    .position();

                let target_position = self
                    .target(target)
                    .expect("explosion target must exist")
                    .position();

                let distance = center.distance_to(target_position);

                falloff.multiplier(distance, radius_m)
            }
        }
    }
}

impl Default for TargetContext {
    fn default() -> Self {
        Self::isolated()
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum DamageCondition {
    Always,

    TargetHealthAbove { fraction: f64 },

    TargetIsBoss,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct FinalDamageModifier {
    pub condition: DamageCondition,

    /// Additional damage per stack.
    ///
    /// 0.75 means +75%.
    pub bonus_per_stack: f64,

    pub stacks: u32,
}

impl FinalDamageModifier {
    pub fn multiplier_for(&self, target: &Target) -> f64 {
        let applies = match self.condition {
            DamageCondition::Always => true,

            DamageCondition::TargetHealthAbove { fraction } => target.health_fraction() > fraction,

            DamageCondition::TargetIsBoss => target.is_boss(),
        };

        if applies {
            1.0 + self.bonus_per_stack * f64::from(self.stacks)
        } else {
            1.0
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TotalDamageProc {
    pub kind: ProcKind,
    pub base_chance: f64,
    pub damage_multiplier: f64,
    pub proc_coefficient: f64,
    pub targeting: AttackTargeting,
    pub timing: EventTiming,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct BleedProc {
    pub base_chance: f64,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum OnHitEffect {
    TotalDamage(TotalDamageProc),
    Bleed(BleedProc),
}

#[derive(Debug, Clone, PartialEq)]
pub struct GeneratedHit {
    pub source: ProcKind,
    pub hit: Hit,
    pub targeting: AttackTargeting,
    pub timing: EventTiming,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Bleed {
    pub target: TargetId,
    pub duration_seconds: f64,
    pub ticks_per_second: f64,
    pub damage_per_tick: f64,
}

impl Bleed {
    pub fn nominal_ticks(&self) -> f64 {
        self.duration_seconds * self.ticks_per_second
    }

    pub fn nominal_total_damage(&self) -> f64 {
        self.nominal_ticks() * self.damage_per_tick
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum GeneratedEffect {
    Hit(GeneratedHit),
    Bleed(Bleed),
}

#[derive(Debug, Clone, PartialEq)]
pub struct ScheduledEvent {
    pub time: Duration,
    pub effect: GeneratedEffect,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct EventQueue {
    events: Vec<ScheduledEvent>,
}

impl EventQueue {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn len(&self) -> usize {
        self.events.len()
    }

    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    pub fn schedule_at(&mut self, time: Duration, effect: GeneratedEffect) {
        self.events.push(ScheduledEvent { time, effect });
    }

    pub fn schedule_after(
        &mut self,
        current_time: Duration,
        delay: Duration,
        effect: GeneratedEffect,
    ) {
        let time = current_time
            .checked_add(delay)
            .expect("combat event time overflow");

        self.schedule_at(time, effect);
    }

    pub fn iter(&self) -> impl Iterator<Item = &ScheduledEvent> {
        self.events.iter()
    }

    /// Remove and return every event occurring at the
    /// earliest timestamp.
    ///
    /// Events in the returned Vec are simultaneous.
    pub fn pop_next_batch(&mut self) -> Option<(Duration, Vec<ScheduledEvent>)> {
        let next_time = self.events.iter().map(|event| event.time).min()?;

        let mut batch = Vec::new();
        let mut remaining = Vec::with_capacity(self.events.len());

        for event in self.events.drain(..) {
            if event.time == next_time {
                batch.push(event);
            } else {
                remaining.push(event);
            }
        }

        self.events = remaining;

        Some((next_time, batch))
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ProcOutcome {
    pub probability: f64,
    pub effects: Vec<GeneratedEffect>,
}

impl ProcOutcome {
    pub fn hits(&self) -> impl Iterator<Item = &GeneratedHit> {
        self.effects.iter().filter_map(|effect| match effect {
            GeneratedEffect::Hit(hit) => Some(hit),
            _ => None,
        })
    }

    pub fn bleeds(&self) -> impl Iterator<Item = &Bleed> {
        self.effects.iter().filter_map(|effect| match effect {
            GeneratedEffect::Bleed(bleed) => Some(bleed),
            _ => None,
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ResolvedHit {
    pub source: ProcKind,
    pub hit: Hit,
    pub targeting: AttackTargeting,
    pub effects: Vec<ResolvedEffect>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ResolvedEffect {
    Hit(ResolvedHit),
    Bleed(Bleed),
}

impl ResolvedEffect {
    pub fn total_damage(&self) -> f64 {
        match self {
            ResolvedEffect::Hit(resolved_hit) => {
                resolved_hit.hit.final_damage
                    + resolved_hit
                        .effects
                        .iter()
                        .map(ResolvedEffect::total_damage)
                        .sum::<f64>()
            }

            ResolvedEffect::Bleed(bleed) => bleed.nominal_total_damage(),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct CombatOutcome {
    pub probability: f64,
    pub effects: Vec<ResolvedEffect>,
}

impl CombatOutcome {
    pub fn total_generated_damage(&self) -> f64 {
        self.effects.iter().map(ResolvedEffect::total_damage).sum()
    }

    pub fn total_damage_with_root(&self, root: &Hit) -> f64 {
        root.final_damage + self.total_generated_damage()
    }
}
