
class pc_item:
    def __init__(self, 
                 name,
                 chance,
                 stat_list,
                 proc_coefficient,
                 damage,
                 damage_increase_per_stack,
                 proc_add_list,
                 tag):

        self.name = name
        self.chance = chance
        self.stat_list = stat_list
        self.proc_cofficient = proc_coefficient 
        self.proc_add_list = proc_add_list
        self.damage = damage
        self.damage_increase_per_stack = damage_increase_per_stack
        self.tag = tag 

soldier_syringe = pc_item('Soldier Syringe',
                          'Permanent',
                          ['Attack Speed'],
                          None,
                          [0.15],
                          [0.15],
                          ['Linear'],
                          ['Damage'])
tougher_times = pc_item('Tougher Times',
                          'Permanent',
                          ['Block Chance'],
                          None,
                          [0.15],
                          [0.15],
                          ['Hyperbolic'],
                          ['Utility', 'BrotherBlacklist'])

monster_tooth = pc_item('Monster Tooth',
                          'OnKillEffect',
                          ['Health per Orb'],
                          None,
                          [0.02],
                          [0.02],
                          ['Linear'],
                          ['Healing', 'OnKillEffect'])
lens_makers_glasses = pc_item("Lens-Maker's Glasses",
                          'OnAttack',
                          ['Critical Chance'],
                          None,
                          [0.10],
                          [0.10],
                          ['Linear'],
                          ['Damage'])
pauls_goat_hoof = pc_item("Paul's Goat Hoof",
                          'OnMove',
                          ['Movement Speed'],
                          None,
                          [0.14],
                          [0.14],
                          ['Linear'],
                          ['Utility'])
bustling_fungus = pc_item('Bustling Fungus',
                          'OnStandStill',
                          ['Health per Second'],
                          None,
                          [0.045],
                          [0.0225],
                          ['Linear'],
                          ['Healing', 'AIBlacklist'])
crowbar = pc_item('Crowbar',
                          'On90%HP',
                          ['Damage'],
                          None,
                          [0.75],
                          [0.75],
                          ['Linear'],
                          ['Damage'])
tri_tip_dagger = pc_item('Tri-Tip Dagger',
                          'OnAttack',
                          ['Chance to Bleed'],
                          None,
                          [0.10],
                          [0.10],
                          ['Linear'],
                          ['Damage'])
warbanner = pc_item('Warbanner',
                          'OnLevelUp',
                          ['Radius'],
                          None,
                          [16],
                          [8],
                          ['Linear'],
                          ['Utility', 'AIBlacklist', 'TurretBlacklist'])
cautious_slug = pc_item('Cautious Slug',
                          'OnOutsideCombat',
                          ['Health Regen'],
                          None,
                          [3],
                          [3],
                          ['Linear'],
                          ['Healing'])
personal_shield_generator = pc_item('Personal Shield Generator',
                          'OnPermanent',
                          ['Shield'],
                          None,
                          [0.08],
                          [0.08],
                          ['Linear'],
                          ['Utility'])
medkit = pc_item('Medkit',
                          'OnTakeDamage',
                          ['Heal'],
                          None,
                          [0.05],
                          [0.05],
                          ['Linear'],
                          ['Healing'])
gasoline = pc_item('Gasoline',
                          'OnKillEffect',
                          ['Damage', 'Radius'],
                          None,
                          [0.15,12],
                          [0.75,4],
                          ['Linear','Linear'],
                          ['Damage', 'OnKillEffect'])
stun_grenade = pc_item('Stun Grenade',
                          'OnHit',
                          ['Chance'],
                          None,
                          [0.05],
                          [0.05],
                          ['Hyperbolic'],
                          ['Utility', 'AIBlacklist'])
bundle_of_fireworks = pc_item('Bundle of Fireworks',
                          'OnInteractable',
                          ['Fireworks'],
                          None,
                          [8],
                          [4],
                          ['Linear'],
                          ['Damage', 'AIBlacklist', 'InteractableRelated'])
energy_drink = pc_item('Energy Drink',
                          'OnSprint',
                          ['Sprint Speed'],
                          None,
                          [0.25],
                          [0.25],
                          ['Linear'],
                          ['Utility', 'SprintRelated'])
backup_magazine = pc_item('Backup Magazine',
                          'Permanent',
                          ['Charge'],
                          None,
                          [1],
                          [1],
                          ['Linear'],
                          ['Utility'])
sticky_bomb = pc_item('Sticky Bomb',
                          'Permanent',
                          ['Chance'],
                          None,
                          [0.05],
                          [0.05],
                          ['Linear'],
                          ['Damage'])
#Update this item
rusted_key = pc_item('Rusted Key',
                          'Permanent',
                          [''],
                          None,
                          [0.25],
                          [0.25],
                          ['Linear'],
                          ['Utility', 'AIBlacklist','OnStageBeginEffect'])
armor_piercing_rounds = pc_item('Armor-Piercing Rounds',
                          'OnBossDamage',
                          ['Damage'],
                          None,
                          [0.20],
                          [0.20],
                          ['Linear'],
                          ['Damage', 'AIBlacklist'])
topaz_brooch = pc_item('Topaz Brooch',
                          'OnKillEffect',
                          ['Barrier'],
                          None,
                          [15],
                          [15],
                          ['Linear'],
                          ['Utility', 'Healing', 'OnKillEffect'])
focus_crystal = pc_item('Focus Crystal',
                          'In13M',
                          ['Damage'],
                          None,
                          [0.20],
                          [0.20],
                          ['Linear'],
                          ['Damage'])
bison_steak = pc_item('Bison Steak',
                          'Permanent',
                          ['Health'],
                          None,
                          [25],
                          [25],
                          ['Linear'],
                          ['Healing'])
repulsion_armor_plate = pc_item('Repulsion Armor Plate',
                          'OnTakingDamage',
                          ['Damage Reduction'],
                          None,
                          [5],
                          [5],
                          ['Linear'],
                          ['Utility'])
mocha = pc_item('Mocha',
                          'Permanent',
                          ['Attack Speed', 'Movement Speed'],
                          None,
                          [0.075, 0.07],
                          [0.075, 0.07],
                          ['Linear','Linear'],
                          ['Damage','Utility'])
#Unique item thing
power_elixer = pc_item('Power Elixer',
                          'On25%HP',
                          ['Damage'],
                          None,
                          [0.20],
                          [0.20],
                          ['Linear'],
                          ['Healing','LowHealth','AIBlacklist'])
delicate_watch = pc_item('Delicate Watch',
                          'On25%HP',
                          ['Damage'],
                          None,
                          [0.20],
                          [0.20],
                          ['Linear'],
                          ['Damage','LowHealth'])
oddly_shaped_opal = pc_item('Oddly-shaped Opal',
                          'OnOutsideCombat',
                          ['Armor'],
                          None,
                          [100],
                          [100],
                          ['Linear'],
                          ['Utility'])
roll_of_pennies = pc_item('Roll of Pennies',
                          'OnTakingDamage',
                          ['Base Gold'],
                          None,
                          [3],
                          [3],
                          ['Linear'],
                          ['Utility','AIBlacklist'])

